// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var loginModule;

  loginModule = angular.module('login', []);

  loginModule.constant('baseRemoteURL', 'http://localhost:8080/calculadora');

  loginModule.controller('LoginCtrl', [
    '$rootScope', '$scope', '$http', 'authService', 'baseRemoteURL', function($rootScope, $scope, $http, authService, baseRemoteURL) {
      return $scope.login = function() {
        return $http.post(baseRemoteURL + 'api/login', {
          username: $scope.authData.username,
          password: $scope.authData.password
        });
      };
    }
  ]);

  loginModule.factory('AuthDataService', [
    'localStorageService', '$base64', '$http', function(localStorageService, $base64, $http) {
      var current_auth_data;
      current_auth_data = localStorageService.get('authorization_token');
      if (current_auth_data) {
        $http.defaults.headers.common['Authorization'] = "Bearer " + current_auth_data;
      }
      return {
        setAuthData: function(authdata) {
          var encoded;
          if (!authdata) {
            return;
          }
          encoded = $base64.encode(authdata);
          localStorageService.set('authorization_token', encoded);
          return $http.defaults.headers.common['Authorization'] = "Bearer " + encoded;
        },
        clearAuthData: function() {
          localStorageService.remove('authorization_token');
          return $http.defaults.headers.common['Authorization'] = '';
        },
        getAuthData: function() {
          return localStorageService.get('authorization_token');
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=logincof.js.map
